[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd backend && python manage.py migrate --noinput && gunicorn reading_platform.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3