# Generated by Django 5.2.6 on 2025-09-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('authentication', '0002_class_classmembership_class_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_assigned',
            field=models.ForeignKey(blank=True, help_text='Class this assignment is assigned to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='authentication.class'),
        ),
    ]
