# Generated by Django 5.2.6 on 2025-09-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The text content of the story')),
                ('grade_level', models.CharField(choices=[('K', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5')], help_text='Target grade level', max_length=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('estimated_reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['grade_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(choices=[('female_1', 'Female Voice 1'), ('female_2', 'Female Voice 2'), ('male_1', 'Male Voice 1'), ('male_2', 'Male Voice 2')], default='female_1', max_length=20)),
                ('file_path', models.CharField(help_text='Path to the audio file in storage', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Audio duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='stories.story')),
            ],
            options={
                'unique_together': {('story', 'voice_type')},
            },
        ),
    ]
