# Generated by Django 5.2.6 on 2025-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='accuracy_score',
            field=models.IntegerField(blank=True, help_text='Accuracy score from 1-5', null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='Which attempt this is for the student'),
        ),
        migrations.AddField(
            model_name='recording',
            name='fluency_score',
            field=models.IntegerField(blank=True, help_text='Fluency score from 1-5', null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade assigned by teacher (excellent, good, needs_practice)', max_length=20, null=True),
        ),
    ]
